// "use client";
// import Link from "next/link";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/sections/navbar";
import Footer from "@/components/sections/footer";
// import { Inter } from "next/font/google";
// import { getServerSession } from "next-auth";
// import { authOptions } from "./api/auth/[...nextauth]/route";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My SaaS App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session = await getServerSession(authOptions);
  return (
    <html lang="en" className="">
      {/* <body className={inter.className}> */}
      <body>
        <Navbar />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
